#lang racket
(require racket/trace)
(require "2.5.1-module-generic-arithmetic.rkt")
(require "2.5.1-module-complex-package.rkt")
(require "2.5.1-module-rational-package.rkt")
(require "2.5.1-module-scheme-number-package.rkt")
(require "2.4.3-module-complex-package-ben.rkt")
(require "2.4.3-module-complex-package-alyssa.rkt")

  

(install-complex-package)
(install-rational-package)
(install-scheme-number-package)
(install-rectangular-package)
(install-polar-package)
(newline)
(define z (make-complex-from-real-imag 1 1       ))
(define w (make-complex-from-mag-ang   2 (/ pi 2)))
(define x (make-rational 1 3))
(define y (make-rational 1 2))
(define a (make-scheme-number 11))
(define b (make-scheme-number 22))
(add z w)
(mul z w)
(add x y)
(mul x y)
(add a b)
(mul a b)
(newline)
(newline)
;(trace get)
z
(magnitude z)
(magnitude x)

