#lang racket
(require compatibility/mlist)
(require racket/trace)


(define (make-table same-key?)
  (define (assoc key records)
    (cond ((null? records) #f)
          ((same-key? key (mcar (mcar records))) (mcar records))
          (else (assoc key (mcdr records)))))
  (let ((local-table (mlist '*table*)))
    (define (lookup key)
      (let ((record (assoc key (mcdr local-table))))
        (if record
          (mcdr record)
          #f)))
    (define (insert! key value)
      (let ((record (assoc key (mcdr local-table))))
        (if record
          (set-mcdr! record value)
          (set-mcdr! local-table (mcons (mcons key value)
                                        (mcdr local-table)))))
      'ok)
    (define (print)
      (display "{")
      (mmap (lambda (record)
             (cond ((not (mpair? record)) (display record)
                                          (display " "))
                   (else (display (mcar record))
                         (display ":")
                         (display (mcdr record))
                         (display " "))))
           local-table)
      (display "}\n"))
    (define (dispatch m)
      (cond ((eq? m 'lookup-proc) lookup)
            ((eq? m 'insert-proc!) insert!)
            ((eq? m 'print-proc) print)
            (else (error "Unknown operation -- TABLE" m))))
    dispatch))

(define operation-table (make-table (lambda (a b) (< (abs (- a b))
                                                     1))))
(define get (operation-table 'lookup-proc))
(define put (operation-table 'insert-proc!))
(define print-table (operation-table 'print-proc))

(put 1 2)
(put 3 4)
(put 5 6)
(get 3)
(get 9)
(get 3.5)
(print-table)
